### ISSUE TITLE
cant parse the block... the result is not rendered 

### ISSUE THREAD

**Issue by muhzulzidan** [danielmilner/wp-block-components#5]
{blocks.map((block, index) => {
           if ('WPGraphQL_CoreCodeBlock' === block.__typename) {
             block.attributes.content = block.attributes.codeContent
             delete block.attributes.codeContent
           }
          return <CoreBlock key={index} block={block}></CoreBlock>

it return the following ...
![Screenshot from 2020-03-16 16-50-35](https://user-images.githubusercontent.com/55260315/76738983-8e6d9600-67a6-11ea-8750-ccf39f340ea6.png)

**Comment by danielmilner** [comment]
Do you have any errors in your console log?

**Comment by muhzulzidan** [comment]
i get this error...
![Screenshot from 2020-03-18 07-01-08](https://user-images.githubusercontent.com/55260315/76909518-608f6b00-68e6-11ea-975a-a11709265dc3.png)

i have tried using some html parser... all of it get error and one of it get a n error like "the content should be a string.." somewhere along those lines..not really sure because i tried so many things..

**Comment by danielmilner** [comment]
What does the data from your GraphQL query look like? It appears to be missing the `attributes` prop for one or more of the blocks.

Try using something like the following to render the `CoreBlock` component.

```
{blocks.map((block, index) => {
    if ('WPGraphQL_CoreCodeBlock' === block.__typename) {
        block.attributes.content = block.attributes.codeContent
        delete block.attributes.codeContent
    }
    return <CoreBlock key={index} block={block} />
})}
```

There was a reason why the `codeContent` attribute needs to be changed to `content`, but I can't remember what that is at the moment.

**Comment by danielmilner** [comment]
I found the reason in one of my old tweets.

> The issue seems to stem from the fact that the same GraphQL field has a different type depending on the fragment being returned.

https://twitter.com/danielmilner/status/1164370644923850752?s=20

**Comment by muhzulzidan** [comment]
i do not know why, but i suddenly get this instead... so i download the wp-grapqhl-starter again... 

![Screenshot from 2020-03-19 22-56-11](https://user-images.githubusercontent.com/55260315/77080974-f20cf300-6a34-11ea-91a9-09ec0d5b171b.png)


then i still got an error and finally i tried it on another starter... still get an error... 
![Screenshot from 2020-03-19 23-04-25](https://user-images.githubusercontent.com/55260315/77081744-0e5d5f80-6a36-11ea-9873-5600b0b80bdb.png)

**Comment by muhzulzidan** [comment]
import React from "react"
import { Link, graphql,  } from "gatsby"

import { CoreBlock } from 'wp-block-components';
import Layout from "../components/layout"
import SEO from "../components/seo"
// import { renderHtmlToReact } from "../utilis/html"
import ParseHTML from "../components/htmlparsers"
const SecondPage = ({data}) => {
  const postData = data.wpgraphql.post
  const { title, blocks,  excerpt, content } = postData
  return (
  <Layout>
    <SEO title={title} description={excerpt}/>
    
    {data.wpgraphql.post.featuredImage && (
      <img src={data.wpgraphql.post.featuredImage.mediaItemUrl} alt={title} />
    )}

    <h1 > {ParseHTML(title)}</h1>
     <div  >{ParseHTML(content)}</div>


{blocks.map((block, index) => {
    if ('WPGraphQL_CoreCodeBlock' === block.__typename) {
        block.attributes.content = block.attributes.codeContent
        delete block.attributes.codeContent
    }
    return <CoreBlock key={index} block={block} />
})}
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)}

export default SecondPage

// export const headingBlocks = graphql`
// fragment headings on WPGraphQL_CoreHeadingBlock {
//           originalContent
//         }`

export const query = graphql`
fragment headings on WPGraphQL_CoreHeadingBlock {
          attributes {
            content
            className
            anchor
            level
          }
          name
        }
  query($databaseId: ID!) {
    wpgraphql {
      post(id: $databaseId, idType: DATABASE_ID) {
        title
        date
        content(format: RENDERED)
        blocks {
          __typename
          ...headings
      }
        categories {
          edges {
            node {
              name
            }
          }
        }
        excerpt(format: RENDERED)
        featuredImage {
          altText
          title(format: RENDERED)
          mediaItemUrl
          slug
        }
      }
    }
  }
  
`


// import React from "react"
// import { graphql } from "gatsby"
// import Layout from "../components/layout"

// export const query = graphql`
//   query($id: ID!) {
//     wpgraphql {
//       post(id: $id) {
//         title
//         content
//       }
//     }
//   }
// `

// const PostTemplate = ({ data }) => {
//   const { title, content } = data.wpgraphql.post
//   return (
//     <Layout>
//       <h1 dangerouslySetInnerHTML={{ __html: title }} />
//       <div dangerouslySetInnerHTML={{ __html: content }} />
//     </Layout>
//   )
// }

// export default PostTemplate
